services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=onlinemarket'
      - 'MYSQL_PASSWORD=Coco1224'
      - 'MYSQL_ROOT_PASSWORD=Coco1224'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
